openapi: "3.0.0"
info:
  version: 1.0.0
  title: Worbli API
  description: Worbli Portal API
  termsOfService: http://worbli.io/terms/
  contact:
    name: Worbli API Team
    email: info@worbli.io
    url: http://worbli.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: '{Protocol}://{Environment}/api/{Version}'
    variables:
      Protocol:
        enum:
          - http
          - https
        default: https
      Environment:
          enum:
            - dev.worbli.io
            - uat.worbli.io
            - localhost:9000
          default: dev.worbli.io
      Version:
          enum:
            - v1
            - v2
            - v3
          default: v3
paths:
  /visitor/signin:
    post:
      tags:
        - Visitors
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email: 
                  type: string
                password:
                  type: string
            example:
              email: test@worbli.io
              password: password1234!

      responses:
        '200':
          description: login response
          content:
            application/json:
              schema:
                required:
                  - data
                  - email
                  - state
                properties:
                  data: 
                    type: boolean
                  email:
                    type: string
                  state:
                    type: object
                  
              example:
                data: true
                email: test@worbli.io
                state: 
                  identity: 'notSubmitted'
                  netowrk: 'noAccess'
        '400':
          description: fail response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /visitor/join:
    post:
      tags:
        - Visitors
      requestBody:
        description: Join credentials
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
                - terms
                - marketing
              properties:
                email: 
                  type: string
                password:
                  type: string
                terms:
                  type: boolean
                marketing:
                  type: boolean
            example:
              email: test@worbli.io
              password: password1234!
              terms: true
              marketing: false
      responses:
        '200':
          description: join response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: join response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /visitor/forgot:
    post:
      tags:
        - Visitors
      requestBody:
        description: Visitor forgot password
        required: true
        content:
          application/json:
            schema:
              required:
                - email
              properties:
                email: 
                  type: string
            example:
              email: test@worbli.io
      responses:
        '200':
          description: forgot password response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: forgot password response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /user/password:
    put:
      tags:
        - User
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      requestBody:
        description: User sets a new password
        required: true
        content:
          application/json:
            schema:
              required:
                - password
              properties:
                password: 
                  type: string
            example:
              password: password1234!
      responses:
        '200':
          description: new password response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: new password response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /user/profile/{id}:
    get:
      tags:
        - User
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true
        - in: path
          name: id
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: new password response
          content:
            application/json:
              schema:
                required:
                  - email
                properties:
                  email: 
                    type: string
              example:
                email: test@worbli.io

        '400':
          description: new password response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /user/profile:
    post:
      tags:
        - User
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true
      requestBody:
        description: User saves their profile
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
                - newPassword
              properties:
                email: 
                  type: string
                password:
                  type: string
                newPassword:
                  type: boolean
            example:
              email: test@worbli.io
              password: password1234!
              newPassword: newPassword1234!

      responses:
        '200':
          description: save profile response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: save profile response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /user/verify:
    post:
      tags:
        - User
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /identity/image:
  # todo: add image upload
    post:
      tags:
        - Identity
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /identity/application:
    # todo: add json in requestBody
    post:
      tags:
        - Identity
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /identity/documents:
    # todo: add country paremeter in header
    get:
      tags:
        - Identity
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /network/account:
    # todo: add country paremeter in header
    post:
      tags:
        - Network
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /network/check:
    # todo: add name paremeter in header
    post:
      tags:
        - Network
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /user/state:
    # todo: add id paremeter in header
    get:
      tags:
        - User
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false



  /mobile/sms:
    # todo: add name paremeter in header
    post:
      tags:
        - Mobile
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: sms sent recipt
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: sms sent recipt
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /mobile/shortcode:
    get:
      tags:
        - Mobile
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: get shortcode
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: get shortcode
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false

        
  /health/ready:
    # todo: fix this up
    get:
      tags:
        - Health
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false
  /health/live:
    # todo: fix this up
    get:
      tags:
        - Health
      parameters:
        - in: header
          name: Authorization
          description: Bearer jwtToken
          schema:
            type: string
          example:
            Authorization: Bearer jwttoken.sdfsdf.sdfsdf
          required: true

      responses:
        '200':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: true

        '400':
          description: verify email response
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data: 
                    type: boolean
              example:
                data: false